### ISSUE TITLE
Any reason why it's running on torch 1.7.0?

### ISSUE THREAD

**Issue by sumukund** [astaka-pe/Dual-DMP#4]
Would it be possible to run this on torch 1.11.0 or higher?

**Comment by astaka-pe** [comment]
@sumukund 
We are using torch 1.7.0 which supports our CUDA 10.2 environment, so it may be possible to build on the newer version. Please note the dependencies between torch, torch-geometric and cuda.
You may also need to rewrite a part of the code because some torch functions have changed in the newer version.
